### ISSUE TITLE
LineString boundingbox returns WORLD_180E180W

### ISSUE THREAD

**Issue by ceilfors** [spatial4j/spatial4j#110] opened 2015-06-14 22:55 UTC
The below code is returning wrong bounding box. It happens when `LongitudeRange.expandTo` is called and it's returning `WORLD_180E180W`.

*Code*
```
def spatialContext = SpatialContext.GEO
        def line = spatialContext.makeLineString([spatialContext.makePoint(0.0, 0.0), spatialContext.makePoint(0.0, 0.0), spatialContext.makePoint(0.0, 0.0)])
        println line.boundingBox
```

*Output*
Rect(minX=-180.0,maxX=180.0,minY=0.0,maxY=0.0)

**Comment by dsmiley** [comment] 2015-06-16 05:02
This is a duplicate of #77 .  It's probably top of the bug list and a solution is not obvious but I have some in-progress code. I hope to get to within a month or so.

**Closed by dsmiley** 2015-06-16 05:02 UTC

**Comment by ceilfors** [comment] 2015-06-16 09:44
If you are hitting this issue, I'm currently making the list unique before calling the API to workaround the bug.
